name: Create Release Tag

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release-tag:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: [ubuntu-latest]
    permissions:
      contents: write  # 태그 생성을 위한 권한
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up environment variables
        run: |
          echo "TAG=${GITHUB_HEAD_REF#release/}" >> $GITHUB_ENV

      - name: Create release tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
